### ISSUE TITLE
Support Ftrl optimizer for Embedding

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1019]
According to [design doc](https://github.com/wangkuiyi/elasticdl/blob/develop/elasticdl/doc/distributed_embedding_layer_design.md#support-slots-in-optimizer), native tensorflow optimizers which have slot variables are not supported in `elasticdl.Embedding`. We need to implement some common optimizers, including Adam and FTRL.

**Comment by mhaoli** [comment]
According to #1078, we can support slots in optimizer in a general way, rather than implementing every TensorFlow optimizer in ElasticDL.

After PR #1161, we have already supported Ftrl in ElasticDL.
