### ISSUE TITLE
Save checkpoint from Redis

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1020]
This is an issue to solve for the distributed embedding layer as mentioned in [design doc](https://github.com/wangkuiyi/elasticdl/blob/develop/elasticdl/doc/distributed_embedding_layer_design.md#issues-to-solve).

**Comment by ywskycn** [comment]
@skydoorkai do we still need this?

**Comment by skydoorkai** [comment]
If we want to keep using Redis, it is needed.

**Comment by ywskycn** [comment]
Close as we'll remove Redis.
