### ISSUE TITLE
elasticdl.layer.Embedding uses pre-created tf.Variable for BET to avoid using tape.watch

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1100]
This should work but need to test.

Also, if the model uses an embedding layer more than once, we need to dynamically add tf.Variable. One way is to fail the layer.call if there are not enough tf.Variables created, add an extra tf.Variable, and run mode.call using the same training data batch again.

**Comment by mhaoli** [comment]
This issue is the same as #1188.
