### ISSUE TITLE
Provide a 101 user guide

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1115]
Currently, there are some development guides in our repo. But it lacks guide doc for newcomers.
Running a mnist training task in a local kubernetes environment is a good start. It will help users know some key concepts of ElasticDL with his/her own laptop.

**Comment by terrytangyuan** [comment]
This tutorial can also be included (needs to be refurnished I think): https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/doc/model_building.md
