### ISSUE TITLE
Add arguments for async-SGD and pass them to master/worker

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1136]
According to [design doc](https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/doc/async_sgd_design.md#add-arguments-for-elasticdltrain), add 3 arguments:

- --use_async, default=False, help="True for asynchronous SGD, False for synchronous SGD"
- --lr_staleness_modulation, default=False, help="If True, master will modulate learning rate with staleness in asynchronous SGD"
- --get_model_frequency, default=1, help="worker will get_model from PS every this steps."

Pass `use_async` and `lr_staleness_modulation` to master.
Pass `use_async` and `get_model_frequency` to worker.

**Comment by chunyang-wen** [comment]
`async` is a reserved keyword. Is it better changed to `synchronization_method`?

Use `use_async` instead.
