### ISSUE TITLE
Refine current embedding service

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1215]
Now, our embedding service has strong dependences on Redis.

```python
def lookup_embedding(keys=[], embedding_service_endpoint=None, parse_type=np.float32)

def update_embedding(keys=[], embedding_vectors=[], embedding_service_endpoint=None, set_if_not_exist=False)
```

There is an `embedding_service_endpoint` argument in lookup_embedding/update_embedding method.

However, another kv store implementation may not need such `embedding_service_endpoint`. We should keep the interface of embedding service clean and general.

Besides, Redis related code logic is in embedding_service, which need to be removed to another module. This will make the embedding_service module cleaner.

**Comment by mhaoli** [comment]
Closing this issue as we have already remove embedding service.
