### ISSUE TITLE
Support async SGD in  Optimizer Wrapper

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1216]

**Comment by mhaoli** [comment]
We can support async SGD in `OptimizerWrapper`. But it seems hard to make `OpitimizerWrapper` to be thread-safe for embedding table. We can make `OptimizerWrapper` to be thread-safe for non-embedding variables now.

We may find whether there is a way to make it to be thread-safe for embedding table after we implement PS.
