### ISSUE TITLE
Add unit test for data reader

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1223]

**Comment by brightcoder01** [comment]
Include RecordIODataReader and ODPSDataReader

**Comment by terrytangyuan** [comment]
@brightcoder01 There are already some tests in `odps_data_reader_test.py` for both `RecordIODataReader` and `ODPSDataReader`. Although maybe we should probably move tests related to RecordIO to another file.

What other tests are you planning to add?

**Comment by brightcoder01** [comment]
@terrytangyuan I see. There will be no more unit test to be added for data reader. It would be better to rename odps_data_reader_test.py to data_reader_test.py.
Just close this issue.
