### ISSUE TITLE
Separate EmbeddingService into two component

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1224]
Currently the EmbeddingService take charge of two work items:
1.  Create the Redis pod (Invoke in Master POD)
2. Execute shell command to start the Redis process (Invoke in created Redis POD)

It would be better to separate these two methods into two components.

https://github.com/sql-machine-learning/elasticdl/blob/a25baf275b0f9b288009d2694deaf9f27c3b832e/elasticdl/python/master/embedding_service.py#L57-L99

**Comment by terrytangyuan** [comment]
@brightcoder01 Isn't this already done in https://github.com/sql-machine-learning/elasticdl/pull/1194?

**Comment by terrytangyuan** [comment]
cc @QiJune to double check

**Comment by QiJune** [comment]
Yes, exactly. I want to refine the code in #1194. However, I find that the final target is to refactor the parameter server logic. And this is not very fully clear now. So, I stop my work temporarily. We'd better to coding this part after the complete parameter server design.

**Comment by brightcoder01** [comment]
@terrytangyuan @QiJune OK, I'll close the duplicated issue. Let's track this refactor work in #1194
