### ISSUE TITLE
Ensure records per task to be integral multiple of mini-batch size.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1232]
Currently, EDL train command contains two parameters: minibatch_size and records_per_task. Because there is no constraint between the value of these two parameters(such as records_per_task = 10, minibatch_size = 8), the records in one mini-batch may come from two tasks.
In order to make the process logic simple and clear, we make sure that records_per_task to be integral multiple of minibatch_size. But we can't assume that user will set these two parameter according to the constraints. Change the parameter name from records_per_task to minibatch_count_per_task.

**Comment by chunyang-wen** [comment]
What is the problem if one mini-batch may come from two tasks?

**Comment by brightcoder01** [comment]
> What is the problem if one mini-batch may come from two tasks?

- If an evaluation task comes after a training task, it's complicated to handle the mini-batch crossing two different types of task.

- If the process of the mini-batch crossing two training tasks failed, shall we set the first task failed or these two tasks failed?

The logic will become more complicated if the data size is not aligned between mini-batch and task (Just like memory alignment). To make it clear, we add the constraint that the mini-batch comes from only one task.
