### ISSUE TITLE
Broken links in documents

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/elasticdl#1246]
I found several bad links in SQLFlow.org with the help of chrome extension[(Check My Links)](https://chrome.google.com/webstore/detail/check-my-links/ojkcdipcgfaekbeaelaapakgnjflfglf):
- In [Data Preparation Design Doc](https://sql-machine-learning.github.io/elasticdl/doc/data_preparation_design/#user_defined_model_file): 
```This file defines the model (404 HERE) that is going to be trained ...```

- In [Design Doc: Distributed Embedding Layer](https://sql-machine-learning.github.io/elasticdl/doc/distributed_embedding_layer_design/#forward-pass)
```... and returns loss and gradients. Here is its code in worker.py (404 HERE)```

- [ElasticDL Model Building](https://sql-machine-learning.github.io/elasticdl/doc/model_building/#elasticdl-model-building)
```To submit an ElasticDL job, a user needs to provide a model file, such as mnist_functional_api.py (first 404) used in this example (second 404) ... ```

- [ElasticDL Model Building](https://sql-machine-learning.github.io/elasticdl/doc/model_building/#model-building-examples)
```
MNIST model using Keras functional API (404)
MNIST model using Keras model subclassing (404)
CIFAR10 model using Keras functional API (404)
CIFAR10 model using Keras model subclassing (404)
```

**Comment by terrytangyuan** [comment]
Thanks! Just fixed these in #1250.
