### ISSUE TITLE
Rename arguments "--*_data_dir" to "--*_data"

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/elasticdl#1248]
Currently, if we want to use ODPS data source, we can pass ODPS table names to "--*_data_dir" arguments instead of previously passing file directories if we want to use RecordIO files as data source. I am proposing the following changes so the data sources are not "file"-dependent:
```
training_data_dir -> training_data
evaluation_data_dir -> evaluation_data
prediction_data_dir -> prediction_data
```
We can add help information like this:
```
This can be either the data directory that contains RecordIO files or an ODPS table name used for training.
```
If there are any suggestions on other names, please let me know in this issue as well.

**Comment by chunyang-wen** [comment]
Is it better to append a string "path" at the end?

**Comment by terrytangyuan** [comment]
@chunyang-wen But in the ODPS case, this should be a table name instead. Either a "path" or "directory" doesn't make much sense.

**Comment by chunyang-wen** [comment]
@terrytangyuan For ODPS, path=odps://project.table. Previously we use path for ODPS table. I agree with you.

**Comment by ywskycn** [comment]
Let's rename the parameter.
