### ISSUE TITLE
How to do evaluation

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1252]
Users usually do an evaluation after several steps of training to see the performance of the model. Besides, when doing checkpoint, we usually want to make an evaluation of the checkpoint.

So, the evaluation might have two kinds:

- Evaluation when doing checkpoint. 

Here, we should introduce a global barrier to sync all workers and pservers. And then, master sends evaluation task to workers. Workers just pull parameters from pservers and will not send gradient. And the evaluation metric is calculated in master.

- Other Evaluation

We allow some in-consistency, some workers do evaluation, some workers do training, pservers still update the model. The evaluation metric is calculated in worker locally.

**Comment by workingloong** [comment]
I summarize the existing evaluation design in EDL and some proposals are given in the 
https://github.com/workingloong/elasticdl/blob/worker_task_execution/doc/evaluation_design.md
