### ISSUE TITLE
Evaluation minibatches may be calculated repeatedly

### ISSUE THREAD

**Issue by mhaoli** [sql-machine-learning/elasticdl#1259]
Currently, each task contains multiple minibatches. In the evaluation phase, workers calculate each minibatch in turn. Every time a minibatch calculation is completed, the worker immediately passes the calculated evaluation metrics to the master. When the worker completes all the minibatches in a task, the worker tells the master the results of the entire task.
If a worker A is killed in the process of calculating a task, the master will find another worker B to calculate the failed task, but it will not clear the metrics of the minibatch already calculated in the task. So some minibatches are calculated both by worker A and worker B, which will lead to errors in the final evaluation metrics.

**Comment by chunyang-wen** [comment]
Interesting. I think workers should report results per task as the task is the minimum unit watched by the master.

**Comment by mhaoli** [comment]
> Interesting. I think workers should report results per task as the task is the minimum unit watched by the master.

Agree. In evaluation phase, worker should report results per task.
