### ISSUE TITLE
Switch to use AUTOTUNE instead of hard-coded buffer_size in `prefetch()`

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/elasticdl#1297]
Currently `Worker` calls `prefetch(1)` on the batched `tf.data.Dataset` with hard-coded `buffer_size=1`. Based on [TensorFlow data performance guide](https://www.tensorflow.org/guide/data_performance#map_and_interleave_prefetch_shuffle):
> The number of elements to prefetch should be equal to (or possibly greater than) the number of batches consumed by a single training step. You could either manually tune this value, or set it to tf.data.experimental.AUTOTUNE which will prompt the tf.data runtime to tune the value dynamically at runtime.

We should probably switch to use `tf.data.experimental.AUTOTUNE` instead to maximize the benefits of overlapping the work of a "producer" with the work of a "consumer" at runtime.

cc: @skydoorkai What do you think?

**Comment by skydoorkai** [comment]
Currently,  each ElasticDL worker only consumes one batch data for the forward pass. `prefetch(1)` is enough. TF uses legacy autotuner for `tf.data.experimental.AUTOTUNE` for now. We can wait until it is not experimental to see if that will benefit ElasticDL.
