### ISSUE TITLE
Generate new checkpoint file

### ISSUE THREAD

**Issue by mhaoli** [sql-machine-learning/elasticdl#1299]
Currently, ElasticDL saves its model in the form of protobuf message `Model`. 

PR #1263 modifies the protobuf definition. We should re-generate the checkpoint file in `elasticdl/python/tests/testdata`.

At the same time, we can try that automatically generating checkpoints for each integration test.

**Comment by chunyang-wen** [comment]
Please add the version information for the exported checkpoint. If we have the version information, we can solve related compatibility issues without touching the checkpoints.

**Comment by mhaoli** [comment]
> Please add the version information for the exported checkpoint. If we have the version information, we can solve related compatibility issues without touching the checkpoints.

Do you mean code version?

**Comment by terrytangyuan** [comment]
We should probably document this process too if it's not easy to generate this automatically at this point.

**Comment by mhaoli** [comment]
> We should probably document this process too if it's not easy to generate this automatically at this point.

Added to develop document in PR #1362 . Close this issue. Feel free to re-open it if we find a way to generate checkpoint file automatically.
