### ISSUE TITLE
Support saving the ElasticDL model into SavedModel format.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1310]
The model definition is stored in master and workers. The variable and embedding vector are stored in the parameter server. How to combine these two and save the model into SavedModel file?

**Comment by brightcoder01** [comment]
**Current Status**:
In the current implementation, ElasticDL model use customized embedding layer **elasticdl.python.elasticdl.layers.embedding**. 
```python
batch_embedding = tf.py_function(
            self.lookup_embedding, inp=[unique_ids], Tout=tf.float32
        )
```
RPC is invoked to look up the embedding value from Redis or PS inside Embedding.call. This logic can't be translated to the TF native op.

**Proposal**
Replace the elasticdl.Embedding with tf.keras.layer.Embedding in the model definition while saving the model.

**Comment by QiJune** [comment]
Each PS pod has a local `Parameters` object which stores the shared parameters. I am afraid that ElastiDL will save the sharded parameters in each PS pod as a `Model` protobuf file. Then, we have a  post-processing function to merge these model protobuf files from PS pods into one file, which is compatible with `SaveModel` format.

**Comment by brightcoder01** [comment]
The model export feature is implemented.
