### ISSUE TITLE
[Serving] Utils to restore the SavedModel to the remote storage such as OSS.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1364]

**Comment by terrytangyuan** [comment]
Do we have a public account that we can use for testing OSS on Travis?

**Comment by workingloong** [comment]
> Do we have a public account that we can use for testing OSS on Travis?

Not yet. Maybe we should consult Aliyun developers on whether we can apply for a public account like ODPS for testing. I also wonder how to get user's OSS account to save the trained model to OSS.

**Comment by brightcoder01** [comment]
This issue is already implemented with ElasticDL callbacks.
