### ISSUE TITLE
Provide a way to stop the job

### ISSUE THREAD

**Issue by chunyang-wen** [sql-machine-learning/elasticdl#1492]
Early stop is a mechanism to stop the training process early to prevent overfitting. EalsticDL does not support this right now.

**Comment by terrytangyuan** [comment]
This should be done via a custom callback in #1106 that would define some logic to stop training when certain criteria is met.

**Comment by chunyang-wen** [comment]
Yes. Early stop should be implemented by a callback. This issue tries to address the problem that those callbacks have no way to stop the job elegantly.

**Comment by brightcoder01** [comment]
Currently ElasticDL support `--max_step` argument for early stopping.
