### ISSUE TITLE
Support local debug&run in IDE for ElasticDL model definition.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1561]
At the present, if we want to debug or dry run the model defined in ElasticDL model zoo. We should submit an ElasticDL job to minikube. It's not efficient.
It would be user friendly to support local debug&run.

**Comment by workingloong** [comment]
I have submitted #1586 to implement the feature. You can debug and dry run the model in the model zoo by the following command:
```
python -m elasticdl.python.elasticdl.client train \
  --model_zoo=model_zoo \
  --model_def=dban_model.keras_dban_model.custom_model \
  --minibatch_size=5 \
  --num_minibatches_per_task=5 \
  --num_epochs=2 \
  --training_data=train.csv\
  --validation_data=test.csv\
  --data_reader_params='columns=["features",  "label"]; sep="\t"' \
  --distribution_strategy=Local \
  --job_name=test-edl-changfan \
```
And, i have submitted a issue #1635 to add tutorial to debug and dry run the model.
