### ISSUE TITLE
Support arbitrary `tf.data.Dataset` objects constructed by TensorFlow I/O 

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/elasticdl#1585]
Currently all classes implementing `AbstractDataReader` creates generators/iterators that will be consumed by `tf.data.Dataset.from_generator()`. Even though this is flexible, it maybe hard to support data sources in different formats and reuse existing solutions. 

We should explore supporting any `tf.data.Dataset` that's constructed by users, e.g. through [TensorFlow I/O](https://github.com/tensorflow/io) that has official/native support for different file formats and file systems.

**Comment by terrytangyuan** [comment]
cc @QiJune Can this be supported as part of the data reader refactoring work?

**Comment by QiJune** [comment]
@terrytangyuan I am trying to optimize the speed of odps data reader now. I will take this into consideration in next step refactoring work.
