### ISSUE TITLE
checkpoint directory problem

### ISSUE THREAD

**Issue by xiaoyili** [sql-machine-learning/elasticdl#1614]
parameter_server.py line 79 should be:

        if None not in [
            args.checkpoint_dir,
            args.checkpoint_steps,
            args.keep_checkpoint_max,
        ]:

because keep_checkpoint_max is 0 by default. all(xx, xx, 0) will return false

**Comment by skydoorkai** [comment]
Yes, `args.keep_checkpoint_max` should be removed from `all`. You are welcome to submit a PR for the fix.
