### ISSUE TITLE
Problem submitting two GPU training task 

### ISSUE THREAD

**Issue by xiaoyili** [sql-machine-learning/elasticdl#1619]
I have a cluster of 5 GPUs. Each training task set 1 worker|ps|master only. However, when first job runs, second training job will get "gpu out of memory" error. The system will hang there forever.

NAME                         READY   STATUS      RESTARTS   AGE
test-train-1-master     1/1     Running     0          97m
test-train-1-ps-0       0/1     Completed   0          97m
test-train-1-worker-0   0/1     Completed   0          97m
test-train-2-master     1/1     Running     0          97m
test-train-2-ps-0       0/1     Error       0          96m
test-train-2-worker-0   0/1     Error       0          96m

**Comment by skydoorkai** [comment]
What are the master/ps/worker_resource_request arg values? Try to GPU only in worker_resource_request (and/or ps_resource_request) but not master.

**Comment by xiaoyili** [comment]
Here are the resources args:
      --master_resource_request="cpu=0.2,memory=1024Mi" \
      --master_resource_limit="cpu=1,memory=2048Mi" \
      --worker_resource_request="cpu=1,gpu=1,memory=3072Mi" \
      --worker_resource_limit="cpu=1,gpu=1,memory=3072Mi" \
      --ps_resource_request="cpu=0.2,memory=1024Mi" \
      --ps_resource_limit="cpu=1,memory=2048Mi" \
