### ISSUE TITLE
benchmark of Go and C++ in PS scenario

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1621]
We want to design an experiment to compare the performance of PS implemented by C++ and Go respectively.

### PS Service

```proto
message Tensor {
    string name = 1;
    repeated int32 dim = 2;
    bytes content = 3;
}

message Model {
    repeated Tensor param = 1;
}

service PServer {
    push_gradient(Model) returns (google.protobuf.Empty);
    pull_parameter(google.protobuf.Empty) returns (Model);
}
```

The PS set up a service, it receives gradients from workers, applies the gradients to parameters, and sends parameters to workers.

### Optimizer

We choose two optimizers:

- SGD
- Adam

### PS and worker numbers

We will set different numbers of ps and workers:

- 1 ps + 1 worker
- 1 ps + 2 workers
- 1 ps + 4 workers
- 1 ps + 8 workers
- 1 ps + 16 workers

The workers will send random gradients to PS, and get the latest parameters from PS.

**Comment by skydoorkai** [comment]
Optionally add `lookup_embedding`, and workers will call it between `pull_parameter` and `push_gradient`.

**Comment by brightcoder01** [comment]
Already implemented PS using go, close this issue now.
