### ISSUE TITLE
Clean PS code according to the concepts document

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1722]
We rethink the core concepts of parameter server, and put them to a [doc](https://github.com/sql-machine-learning/elasticdl/blob/develop/docs/designs/concepts.md). And we plan to refactor our codes according to the doc.

Most of the basic proto messages are changed. This will break a lots of unit tests now. We have to modified both Go PS code/Python PS code/Python worker code. Adding a single big PR to fix all the codes is a choice. But it brings a lots of risk, and it's hard to review.

We must change the code base step by step. In each step, we set up small PRs to the code base.

I propose a two-step solution.

Step 1

We add some new messages like IndexedSlices, and add some new fields to current messages. For example, the new Model proto mesages could be:

```proto
message Tensor {
  string name = 1;
  repeated int64 dim = 2;
  bytes content = 3;
  repeated int64 indices = 4;
  TensorDtype dtype = 5;
}

message IndexedSlices {
  Tensor concated_vectors = 1;
  repeated int64 ids = 2;
}

message Model {
  int32 version = 1;  // model updated times
  repeated Tensor param = 2;
  repeated EmbeddingTableInfo embedding_table_info = 3;
  map<string, Tensor> dense_parameters = 4;
  map<string, IndexedSlices> indexed_slices = 5;
}
```

In this way, the Python code is not broken. All current Python related unit tests are good. And we could modify our Go PS code according to the new design.

In this step, some proto messages are redundant. But we keeps the consistency of Python code. We could sends a lot of small PRs to refactor Go code.

Step 2.

We remove redundant fileds of some proto messages, and remove some redundant proto messages.

In this step, the Go PS code is not affected. We only clean the Python code base.

**Comment by mhaoli** [comment]
Maybe we can split Step 2 into 2 steps, step 2 and step 3.

Step 2
Use `numpy.ndarray` and `tf.IndexedSlices` to replace `elasticdl.Tensor` data structure for gRPC services in python code. We can replace them concurrently for different gRPC services.

Step 3
Clean redundant proto messages.

**Comment by QiJune** [comment]
Since Python PS will be replaced with Go PS. We should not put too much time to refactor Python code.

Step 1. 

- Add new fields or new proto messages if needed
- Refactor Go code
- Continue to develop Go PS features, such as checkpoint feature

Step 2. 
- Create a new `worker_gops.py` for only Go PS
- Add necessary util functions for `worker_gops.py`

Step 3.
- After we finishing the development of Go PS, we could safely remove Python PS code, and clean the redundant proto messages.
- clean `worker.py`, and maybe we could seperate a module called `worker_allreduce.py`. Now we have `worker_gops.py` and `worker_allreduce.py`. There may some common logics in these two modules. We could refactor worker related codes at this time.

**Comment by brightcoder01** [comment]
The concept objects are defined in elasticdl.proto.
