### ISSUE TITLE
Should master fail if all workers failed ?

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#1789]
Sometimes, all workers fail due to errors of data or model codes. The master should fail and exit to show the job fails. The user may think the job is running if the master does not fail.

**Comment by skydoorkai** [comment]
Master can know why the worker fails, such as preemption or OOM. For other reasons, the master can assume a worker fails because of some unrecoverable errors. If all workers fail with unrecoverable errors, the master can fail also.
