### ISSUE TITLE
Decouple elasticdl_preprocessing from elasticdl main package.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1921]
elasticdl_preprocessing only depends on TensorFlow. It can be used in elasticdl model training and vanilla tensorflow training.

**Comment by workingloong** [comment]
Use a dependent repo for `elasticdl_preprocessing`?

**Comment by brightcoder01** [comment]
> elasticdl_preprocessing

We can use another setup.py for elasticdl_preprocessing at first.
