### ISSUE TITLE
Don't package datasets into Docker images

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/elasticdl#1947]
https://github.com/sql-machine-learning/elasticdl/blob/develop/docs/tutorials/elasticdl_local.md

Instead, bind mount MNIST dataset on local filesystem to minikube containers.

**Comment by brightcoder01** [comment]
Update the following parts to avoid package the data into docker image. Use volume mount instead.
- Update the elasticdl_local tutorial
- Update the integration testing in travis CI
