### ISSUE TITLE
Should we create a transform folder in sql-machine-learning to contain preprocessing layers?

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#1980]
The `elasticdl_preprocessing` is irrelevant to elastic scheduling. Except for Keras preprocessing layers, It should contain the following components for completeness:
- Data analysis to collect feature statistics.
- Preprocessing layers including Keras layers and PyTorch transformation functions.
- time-series analysis and  preprocessing

So, the logic of this module is similar to [TensorFlow Transform](https://github.com/tensorflow/transform).

**Comment by wangkuiyi** [comment]
sql-machine-learning is an org. We can create repos, but cannot create directories, under an org.

**Comment by brightcoder01** [comment]
Just as the discussion with @wangkuiyi @workingloong , we decide to make `transform` a directory in the elasticdl repo at the current stage. When the content of the folder get richer, we can consider make a separate repo.
