### ISSUE TITLE
Source tree directory structure adjustment

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/elasticdl#1981]
Here is a proposal

```
/python
  elasticdl
    setup.py
    master
    worker
  cli
    setup.py
  transform
    setup.py
/go
  pkg
    ps
  cmd
    ps
/proto
  elasticdl.proto
```

**Comment by wangkuiyi** [comment]
In the above source tree, there are three setup.py files, which generates the following PIP packages

1. elasticdl-cli
   A minimalism package that depends basically on the Kubernetes Python API

1. elasticdl
   This package contains the master, worker, and parameter server programs.  A model contributor, when defining a model zoo Docker image, might write the following Dockerfile

   ```dockerfile
   FROM tensorflow
   RUN pip install elasticdl 
   COPY . /models
   ```

1. transform
   This package is independent with ElasticDL and contains extensions to Keras layers and feature column APIs.  In the future, we might move it out from the ElasticDL repo into a standalone repo.

**Comment by QiJune** [comment]
How about building two pip wheel package elasticdl-cli and transform, and one docker image, elasticdl:latest?

Since ElasticDL is Kubernetes native, all the programs will be executed inside the Docker container. We could pack the master/worker/parameter server programs inside a predefined Docker image. The parameter server is developed by Go. Master and worker are developed by Python. It's not convenient to pack them together.

Users could write the following Dockerfile to add a model.
```
FROM elasticdl:latest
COPY . /models
```

**Comment by workingloong** [comment]
The following proposal is more reasonable. 
- `elasticdl`, `client`, and `transform` are mutually independent, so they should be at the first level. The reader can know they are independent function modules when he views the directory structure.
- The elasticdl wheel package should contain PS go codes and protobuf codes, so those files should be in the `elasticdl` directory. It is more clear to read the codes. The reader only needs to view codes in the `elasticdl` folder if he only cares about the ElasticDL distribution strategy.

```
/elasticdl
  setup.py
  python
    master
    worker
  go
    pkg
      ps
    cmd
      ps
    proto
      elasticdl.proto

/client
  setup.py
  zoo
  train
  evaluate
  predict

/transform
  setup.py
  analysis
  preprocessing
```

**Comment by wangkuiyi** [comment]
> How about building two pip wheel package elasticdl-cli and transform, and one docker image, elasticdl:latest?
> 

Model contributors might not want to use our Docker image as their base image.  Consider the example in https://github.com/sql-machine-learning/elasticdl/issues/1981#issuecomment-641684700

**Comment by wangkuiyi** [comment]
@workingloong I did a comparison between the two ways of group-by-languages and group-by-modules.  They have the same complexity -- so Occam's Razor doesn't help here.  I agree that the group-by-module way makes the codebase easier to read.

<img width="479" alt="Screen Shot 2020-06-10 at 2 26 17 PM" src="https://user-images.githubusercontent.com/1548775/84320346-5ae0a480-ab26-11ea-8420-bb36d0937871.png">

**Comment by wangkuiyi** [comment]
It looks to me that the package `elasticdl/python/data/recordio_gen` should be separated from the package `elasticdl` into a new package, say `datasets`. If so, we are going to have the following standalone Python packages in this repo:

- elasticdl
- elasticdl-client
- zoo
- transform -- how about renaming it into input?
- datasets

How about the following directory structure:

```
/
    elasticdl/
        setup.py
        ps -- .go files
        master -- .py files
        worker -- .py files
        proto -- .proto files
    elasticdl-client/
        setup.py
    zoo/
        setup.py
    input/
        setup.py
    datasets/
         setup.py
```
