### ISSUE TITLE
Polish dev.md - how to build and contribute elasticdl.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#2077]
How to build
- Pull elasticdl:dev from docker repo or build the image by our own.
- Build three pip packages using elasticdl:dev and build.sh

How to contribute
- Make code change locally
- How to run pre-commit locally
- How to run unit test locally
- Coding standard reference

**Comment by wangkuiyi** [comment]
Agree on that we need to polish the development document.

Per the community convention, we should merge the content of dev.md and /elasticdl/README.md into /CONTRIBUTE.md.
