### ISSUE TITLE
Function name style for unit testing.

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#2239]
There are two styles to name the unit testing function in ElasticDL.

- CamelCase like https://github.com/sql-machine-learning/elasticdl/blob/5fac16d29854001f8f68d4a0d514f4f57b95b8eb/elasticdl/python/tests/servicer_test.py#L53
- Underscore like https://github.com/sql-machine-learning/elasticdl/blob/5fac16d29854001f8f68d4a0d514f4f57b95b8eb/elasticdl/python/tests/layer_test.py#L135

We should select one style to write unit tests.  The  underscore style is common in Python like the example in the Python document for unit testing.
https://docs.python.org/3.4/library/unittest.html#basic-example

**Comment by QiJune** [comment]
Vote for the underscore style. It's Pythonic!

**Comment by skydoorkai** [comment]
underscore +1

**Comment by Kelang-Tian** [comment]
https://github.com/sql-machine-learning/elasticdl/blob/5fac16d29854001f8f68d4a0d514f4f57b95b8eb/elasticdl/python/tests/worker_ps_interaction_test.py#L267
unittest in Elasticdl test is underscored style. Maybe we can keep consistent style.

**Comment by workingloong** [comment]
> https://github.com/sql-machine-learning/elasticdl/blob/5fac16d29854001f8f68d4a0d514f4f57b95b8eb/elasticdl/python/tests/worker_ps_interaction_test.py#L267
> 
> 
> unittest in Elasticdl test is underscored style. Maybe we can keep consistent style.

The both styles are in ElasticDL tests.  Like https://github.com/sql-machine-learning/elasticdl/blob/5fac16d29854001f8f68d4a0d514f4f57b95b8eb/elasticdl/python/tests/servicer_test.py#L53

**Comment by workingloong** [comment]
So, it is the underscore style and we should fix CamelCase function names with underscore.

**Comment by brightcoder01** [comment]
We can follow the [Google Python Coding Style](https://google.github.io/styleguide/pyguide.html#316-naming)
