### ISSUE TITLE
Add a tutorial to use ElasticDL to train DeepCTR models on GCloud and Aliyun.

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#2318]
[DeepCTR](https://github.com/shenweichen/DeepCTR) is a popular repo for CTR prediction. DeepCTR uses Keras API to define models and users can only train those models locally now. ElasticDL provides distributed training for Keras models on Kubernetes. So, we can write a tutorial to tell users how to use ElasticDL to train DeepCTR models on the Kubernetes cluster of Google Cloud and Aliyun.

**Comment by xxllp** [comment]
how to use this on an local k8s
