### ISSUE TITLE
API for dynamic sharding

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#2350]
# Sharding for the Training Data

Dynamic sharding is an important role in ElasticDL. However, the dynamic sharding only supports RecordIO files and MaxCompute tables. We should extend dynamic sharding to support more data formats like the jpg of images.

The shard in ElasticDL contains the name, the start index, and the end index. 

```proto
shard {
    name=1;
    start=2;
    end=3;
}
```

We can read data from storage by those 3 elements. The name may be the same for different shards like the MaxCompute table. But the start and end indices must be different for different shards.  So, the start and end indices are sometimes enough for us to use ElasticDL. 

In ElasticDL, the master is responsible for creating shards. So, the master must know the total size of the training data. Using the RecordIO or MaxCompute table, the master can get the size by the  RecordIO and MaxCompute APIs. When we read original images, the master can scan the CSV file where we write the image file paths. However, it is different for the master to get the size of the training data. For example, the image information is saved in a JSON file for COCO dataset. The master should parse the JSON to get the size. So, we should design an API implemented by users to get the total size.

# API for the master to Create Shards

## The supported formats for the master to get the size.

There are 3 formats for the master to get the size of the training data. The master will call the relative readers to scan those files to get the size.

RecordIO
```bash
--trainingdata=/testdata/mnist/train
```

MaxCompute
```bash
--trainingdata=maxcompute_project.elasticdl_train_table
```

Text with the image file paths
```bash
--trainingdata=/testdata/mnist/train/images.csv
```
 
The content in the csv is
```txt
9/img_24723.jpg,9
9/img_15298.jpg,9
9/img_24045.jpg,9
9/img_41811.jpg,9
```

In those cases, the shard will contain the name, start, and end index. Users can read the storage by the name.

## The API defined by users to get the training size.

```Python
def training_data_size():
    with open("annotations/captions_val2014.json") as f:
        data = json.load(f)
    return len(data["annotations"])
```
The master will call the API  to get the total size to create shards before starting the training. In this case, the shard only contains the start and end index. Users need to read the storage by themselves with the start and end index.

# API for the Worker to Get Shards

```python
class DataShardService(object):
    def __init__(self):
        master_addr = os.getenv("MASTER_ADDR")
        worker_id = os.getenv("WORKER_ID")
        self.master_client = MasterClient(
            build_channel(master_addr), worker_id
        )

    def fetch_shard(self):
        """Return a shard from the task manager of the master.
        The shard contains the name, start, and end. For example,
        the name is the table name for MaxCompute or a shard file name for RecordIO.
        Sometimes, the name is evenly a CSV file path and the start is
        the line index of the file.
        """

    def report_batch_done(self):
        """Report the shard completed"""
```

**Comment by brightcoder01** [comment]
The following case may be a csv data or a index file for the image folder. How do we differentiate these two cases?
```
Text with the image file paths

--trainingdata=/testdata/mnist/train/images.csv
```

**Comment by skydoorkai** [comment]
get_training_size() -> training_data_size()

**Comment by workingloong** [comment]
> The following case may be a csv data or a index file for the image folder. How do we differentiate these two cases?
> 
> ```
> Text with the image file paths
> 
> --trainingdata=/testdata/mnist/train/images.csv
> ```

We don't need to differentiate these cases. We can get the size can create shards only if each line in the file contains the information of one record.

```Text
9/img_24723.jpg,9
9/img_15298.jpg,9
9/img_24045.jpg,9
9/img_41811.jpg,9
```

**Comment by brightcoder01** [comment]
Please add an example to show the difference of the Dataset/DataLoader code or other additional configurations between the fixed data sharding (current implementation) and the dynamic data sharding. Our goal is to make the difference as small as possible.
