### ISSUE TITLE
PodManager Observer Pattern

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#2371]
The main responsibility of `PodManager` is to maintain the cluster for ElasticDL distributed job. It interacts with Kubernetes directly.  It calls K8S API to create pods/services for the ElasticDL job cluster, relaunches the pod if required and also watches the event published from Kubernetes.
As the job goes on, there may be some changes happening in the members of Job cluster such as worker / ps. The other components may be interested in this event and do some action according to various events. So we propose to apply the observer design pattern to PodManager.

```Python
import collections

PodInfo = collections.namedtuple(
    "PodInfo",
    (
        "type",
        "id",
        "name",
        "address"
    )
)

ClusterContext = collections.namedtuple(
    "ClusterContext",
    (
        "pod_manager"
    )
)

class PodManager(object):
    def __init__(self):
        self._listeners = []

    def add_listener(self, job_cluster_listener):
        self._listeners.append(job_cluster_listener)
```

Option 1:
```Python
class JobClusterListener(object):
    def on_pod_started(self, job_member, job_cluster_context):
        pass

    def on_pod_completed(self, job_member, job_cluster_context):
        pass

    def on_pod_failed(self, job_member, job_cluster_context):
        pass

    def on_pod_deleted(self, job_member, job_cluster_context):
        pass
```

Option 2:
```Python
class JobClusterListener(object):
    def on_worker_started(self, job_member, job_cluster_context):
        pass

    def on_worker_completed(self, job_member, job_cluster_context):
        pass

    def on_worker_failed(self, job_member, job_cluster_context):
        pass

    def on_worker_deleted(self, job_member, job_cluster_context):
        pass

    def on_ps_started(self, job_member, job_cluster_context):
        pass

    def on_ps_completed(self, job_member, job_cluster_context):
        pass

    def on_ps_failed(self, job_member, job_cluster_context):
        pass

    def on_ps_deleted(self, job_member, job_cluster_context):
        pass
```

Currently, there will be two listeners, no listener observes the event of PS.
- TaskManager: focus on `worker failed event`, reassign the tasks belongs to the failed worker to others
- HorovodRendezvousServer: focus on `worker started/completed/failed/deleted event`, will rebuild the configuration for Horovod AllReduce.

Q&A
1. Why not include alive_worker_addresses in JobClusterContext?
    Not all the listeners cares about this information. And it's a little heavy to build alive_worker_addresses. The listener can get the reference of `pod_manager` in JobClusterContext and call its method to get this information on demand.

**Comment by workingloong** [comment]
How to get `alive_worker_addresses`?

**Comment by skydoorkai** [comment]
1. Option 1 is better.

2. Make the name simple, as there is no job definition in the pod manager. 
JobMember ->PodInfo
JobClusterContext -> just use the reference of pod_manager itself.

**Comment by brightcoder01** [comment]
> alive_worker_addresses

pod_manager will have a method `get_alive_worker_addresses`, the listener can call it on demand.

**Comment by brightcoder01** [comment]
> 1. Option 1 is better.
> 2. Make the name simple, as there is no job definition in the pod manager.
>    JobMember ->PodInfo
>    JobClusterContext -> just use the reference of pod_manager itself.

Rename JobMember to PodInfo, JobClusterContext to ClusterContext.

**Comment by brightcoder01** [comment]
After discussion, we have made agreement on the proposal. Close this issue.
