### ISSUE TITLE
Compare the process of rank 0 selection between Horovod elastic and elasticdl

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#2401]

**Comment by workingloong** [comment]
Can you provide more details?

**Comment by brightcoder01** [comment]
From the horovod [document](https://horovod.readthedocs.io/en/stable/elastic_include.html#modifying-the-training-script-with-state-synchronization), `During rendezvous, older workers will take priority in being assigned worker-0 status to ensure that the state that is broadcast is up to date.`. The strategy is the same between horovod elastic and ElasticDL.

**Comment by brightcoder01** [comment]
We have gotten the conclusion, close this issue.
