### ISSUE TITLE
The worker sends start and end message to the master for AllReduce.

### ISSUE THREAD

**Issue by workingloong** [sql-machine-learning/elasticdl#2445]
Now, users can customize the training loop. Sometimes, users may do some preparation work before starting the training loop. For example, users may need to transform the total images and load the model from a checkpoint. After finishing the training loop, users may need to do post-training work. Those preparation and post-training work may have an influence on the training using AllReduce of other workers.

The master will add the living worker into the ring if the worker starts. However, the worker will not start the training loop immediately for the preparation work. Then, other workers in the ring must wait for the worker which may raise a timeout. 

The master will remove the living worker out of the ring if the worker exists. The worker will not exits if there is post-training work. Other workers may also raise a timeout if there are remaining shards to train.

We can develop a `start` and `end` in the `AllReduceController`. The controller should send a start message to the master before the training loop and send an end message to the master.

```python
class AllReduceController(object):
    def __enter__(self):
        send_start()
    def __exit__(self, exc_type, exc_val, exc_tb):
         send_end()
```

Then, users need to execute the training loop in `with allreduce_controller`:

```python

allreduce_controller = create_elastic_controller(
    batch_size=args.batch_size
)

with allreduce_controller:
    for batch_idx, (data, target) in enumerate(data_loader):
        target = target.type(torch.LongTensor)
    
        # Use the elastic function to wrap the training function with a batch.
        elastic_train_one_batch = allreduce_controller.elastic_run(
            train_one_batch
        )
        loss = elastic_train_one_batch(model, optimizer, data, target)
```

**Comment by brightcoder01** [comment]
I prefer
```python
with allreduce_controller.scope()
```
instead of
```
with allreduce_controller:
```
just like [the API style of TensorFlow DistributeStrategy](https://www.tensorflow.org/guide/distributed_training#using_tfdistributestrategy_with_tfkerasmodelfit)

send_start -> notify_train_loop_start
send_end -> notify_train_loop_end
