### ISSUE TITLE
Evaluation support best exporter

### ISSUE THREAD

**Issue by zuston** [sql-machine-learning/elasticdl#2513]
Now edl evaluation support best exporter?

**Comment by zuston** [comment]
@workingloong Gentle ping.

**Comment by workingloong** [comment]
> Now edl evaluation support best exporter?

Not yet.

**Comment by zuston** [comment]
Pity. Thanks

**Comment by workingloong** [comment]
> Pity. Thanks

But, we have supported the TensorFlow estimator and you can use `tf.estimator` with the best exporter. I will notice you when we finish the tutorial to train `tf.estimator` using ElasticDL on K8s.

**Comment by workingloong** [comment]
You can use [tf.estimator.BestExporter](https://www.tensorflow.org/api_docs/python/tf/estimator/BestExporter) in an estimator model and use ElasticDL to train it by the [tutorial](https://github.com/sql-machine-learning/elasticdl/blob/327a2c7e8d5cb7a5c774bbaf8a842426856847c8/docs/tutorials/elasticdl_estimator.md).
