### ISSUE TITLE
a little question about embedding parameters synchronization

### ISSUE THREAD

**Issue by jasperzhong** [sql-machine-learning/elasticdl#2519]
Great work! [PS design doc](https://github.com/sql-machine-learning/elasticdl/blob/develop/docs/designs/parameter_server.md#embedding-replica) says embedding parameters are replicated across servers and synchronization is needed for consistency. I have some concerns about the synchronization overhead since embedding layers are usually huge. For example, Facebook mentioned that their embedding tables of production may be terabytes in size ([paper link](https://proceedings.mlsys.org/paper/2021/file/b73ce398c39f506af761d2277d853a92-Paper.pdf)).

**Comment by workingloong** [comment]
> Great work! [PS design doc](https://github.com/sql-machine-learning/elasticdl/blob/develop/docs/designs/parameter_server.md#embedding-replica) says embedding parameters are replicated across servers and synchronization is needed for consistency. I have some concerns about the synchronization overhead since embedding layers are usually huge. For example, Facebook mentioned that their embedding tables of production may be terabytes in size ([paper link](https://proceedings.mlsys.org/paper/2021/file/b73ce398c39f506af761d2277d853a92-Paper.pdf)).

Yes, there is the synchronization overhead of huge embedding layers. So, we can adjust the staleness in the gradient update to improve efficiency. For example, the ps can drop the gradient version is stale.
