### ISSUE TITLE
Performance issue in the program

### ISSUE THREAD

**Issue by DLPerf** [sql-machine-learning/elasticdl#2521]
Hello, I found a performance issue in the definition of `RecordIODataReaderTest`, elasticdl/blob/develop/elasticdl/python/tests/data_reader_test.py, [tf.io.FixedLenFeature in the line 70 and 71](https://github.com/sql-machine-learning/elasticdl/blob/4edfde51227c592efb036b69b5b5bcb3aeba9187/elasticdl/python/tests/data_reader_test.py#L70) will be called in the program execution, resulting in  reduced efficiency. I think it should be created before the loop in `RecordIODataReaderTest`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by workingloong** [comment]
You can feel free make a PR to fix it.
