### ISSUE TITLE
Investigate ReportGradient() failure rate

### ISSUE THREAD

**Issue by zhujl1991** [sql-machine-learning/elasticdl#494]
By design, `ReportGradient()` may fail if the worker computes gradients on an outdated model https://github.com/wangkuiyi/elasticdl/blob/597eaf7f6aa91354dd66e031082c880c84449806/elasticdl/python/elasticdl/master/servicer.py#L106-L113 .  `failure_rate = num_of_failed_gradient_report / num_of_total_gradient_report`.

Technically, the larger the `grads_to_wait/num_worker` is, the smaller the `failure_rate` is, the more time training job needs(when `grads_to_wait` is fixed).

In order to guide our users to make this trade-off, we need to investigate this and give them some experimental data.

Some initial result on mnist data:
`--grads_to_wait=2, --num_worker=2`: failure_rate = 27%
`--grads_to_wait=4, --num_worker=2`: failure_rate = 16%

**Comment by ywskycn** [comment]
Close for now. Should be covered by the experiment/report done in #705.
