### ISSUE TITLE
Write a standard distributed TensorFlow program

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/elasticdl#917]
that trains the MNIST model using N workers and a parameter server, as a comparison to ElasticDL.

This program should use TensorFlow's native distributed training mechanism, i.e., workers communicate with the parameter server in the way of TensorFlow's graph partitioning.

**Comment by terrytangyuan** [comment]
@skydoorkai Why is #918 closed? What's left to do for this issue?

**Comment by skydoorkai** [comment]
> @skydoorkai Why is #918 closed? What's left to do for this issue?

It is not fair to compare distributed TensorFlow with training data in local memory with ElasticDL that reads data from remote shared storage. So #918 is closed.
